services:
  db:
    image: postgres:15
    container_name: swift
    restart: always
    environment:
      POSTGRES_USER: userstory
      POSTGRES_PASSWORD: pasword23
      POSTGRES_DB: swift_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - swift-network

networks:
  swift-network:

volumes:
  postgres_data:
    driver: local
